### PR TITLE
Allow plugins to be installed from URL

### PR DESCRIPTION
**Pull request by mayurvaid-redvest**
- This would help in custom plugin or secured environments for eg: may be pulling from artifactory
-  Also allow to pull latest as well

### CODE REVIEW

**Comment by mayurvaid-redvest** [comment]
@pb82  , Can you please review

**Comment by mayurvaid-redvest** [comment]
@pb82  @NissesSenap  Can you please review

**Comment by NissesSenap** [comment]
@mayurvaid-redvest my initial look I think it looks okay. But there are a few to many splits for my brain right now.
Could you write a small test just to show that everything works as intended?

Using the existing use case and your new functionality.

**Comment by mayurvaid-redvest** [comment]
@NissesSenap  , Thanks for reviewing this . Have added the test case Please let me know if anything else is required

**Comment by mayurvaid-redvest** [comment]
@NissesSenap  , Please update and let me know ...Appreciate your help !!

**Comment by NissesSenap** [comment]
So I gave it a try on my client.

You need to use `OS = os.environ.get("OS", platform.system().lower())` or something similar in your tests. Else the tests won't work on any client.

Since I'm a happy Linux user I get.

```shell
FAIL: test_get_plugin_withurl_multiple_withoutversion_reverse (plugins_test.TestGetPlugins)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edvin/go/src/github.com/NissesSenap/grafana-plugin/plugins_test.py", line 136, in test_get_plugin_withurl_multiple_withoutversion_reverse
    self.assertEqual(actual, expected)
AssertionError: Lists differ: [('ht[73 chars]d?os=linux&arch=x86_64', '/tmp/grafana-clock-p[102 chars]ip')] != [('ht[73 chars]d?os=darwin&arch=x86_64', '/tmp/grafana-clock-[103 chars]ip')]

First differing element 0:
('htt[72 chars]d?os=linux&arch=x86_64', '/tmp/grafana-clock-panel_latest.zip')
('htt[72 chars]d?os=darwin&arch=x86_64', '/tmp/grafana-clock-[13 chars]zip')

- [('https://grafana.com/api/plugins/grafana-clock-panel/versions/latest/download?os=linux&arch=x86_64',
?                                                                                    ^  --

+ [('https://grafana.com/api/plugins/grafana-clock-panel/versions/latest/download?os=darwin&arch=x86_64',
?                                                                                    ^^^^

    '/tmp/grafana-clock-panel_latest.zip'),
   ('https://grafana.com/api/plugins/grafana-clock-panel',
    '/tmp/grafana-clock-panel.zip')]

----------------------------------------------------------------------
```

Since you have written your change in the master branch I don't have access to update the PR for you.

**Comment by NissesSenap** [comment]
Thanks for the tests btw, it really makes it easier to verify that everything looks okay :)

**Comment by mayurvaid-redvest** [comment]
> So I gave it a try on my client.
> 
> You need to use `OS = os.environ.get("OS", platform.system().lower())` or something similar in your tests. Else the tests won't work on any client.
> 
> Since I'm a happy Linux user I get.
> 
> ```shell
> FAIL: test_get_plugin_withurl_multiple_withoutversion_reverse (plugins_test.TestGetPlugins)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/edvin/go/src/github.com/NissesSenap/grafana-plugin/plugins_test.py", line 136, in test_get_plugin_withurl_multiple_withoutversion_reverse
>     self.assertEqual(actual, expected)
> AssertionError: Lists differ: [('ht[73 chars]d?os=linux&arch=x86_64', '/tmp/grafana-clock-p[102 chars]ip')] != [('ht[73 chars]d?os=darwin&arch=x86_64', '/tmp/grafana-clock-[103 chars]ip')]
> 
> First differing element 0:
> ('htt[72 chars]d?os=linux&arch=x86_64', '/tmp/grafana-clock-panel_latest.zip')
> ('htt[72 chars]d?os=darwin&arch=x86_64', '/tmp/grafana-clock-[13 chars]zip')
> 
> - [('https://grafana.com/api/plugins/grafana-clock-panel/versions/latest/download?os=linux&arch=x86_64',
> ?                                                                                    ^  --
> 
> + [('https://grafana.com/api/plugins/grafana-clock-panel/versions/latest/download?os=darwin&arch=x86_64',
> ?                                                                                    ^^^^
> 
>     '/tmp/grafana-clock-panel_latest.zip'),
>    ('https://grafana.com/api/plugins/grafana-clock-panel',
>     '/tmp/grafana-clock-panel.zip')]
> 
> ----------------------------------------------------------------------
> ```
> 
> Since you have written your change in the master branch I don't have access to update the PR for you.

Hey Thanks for this  , Have update it @NissesSenap  .. Please validate

**Pull request merged**
